export const TOKEN_ADDRESS = "0xd22F74ffDBC19D5C882b145A0D414a43D2c49982";
export const SURVEY_NFT_ADDRESS = "0x0bc656a9EC41618f72F19c1Eda593403135c4D33";
export const SURVEY_MARKETPLACE_ADDRESS =
  "0x67EB72824BEbDa2B44ACE2e76bc987D4e2A6f66B";
export const SURVEY_ADDRESS = "0x77cc95d0df289e9FcdcEafde90182DF04E0d16e7";
export const SURVEY_ADDRESS_NEW = "0x2f8A585d97DbC8299D2Ab81D5914264bFb5Ffa1e";
export const SURVEY_ABI_NEW = [
  {
    inputs: [
      { internalType: "address", name: "_TokenAddress", type: "address" },
      { internalType: "uint256", name: "_validatorsFee", type: "uint256" },
      { internalType: "uint256", name: "_kycVerificationFee", type: "uint256" },
      { internalType: "address", name: "_commisionAddress", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "surveyURI",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "validator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "surveyID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "answerID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isValidated",
        type: "bool",
      },
      { indexed: false, internalType: "bool", name: "isValid", type: "bool" },
    ],
    name: "AnswerCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "surveyURI",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "surveyID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "planID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "numOfValidators",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "numOfcommisioners",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "numOfresponse",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      { indexed: false, internalType: "bool", name: "nftStatus", type: "bool" },
      { indexed: false, internalType: "bool", name: "exist", type: "bool" },
      { indexed: false, internalType: "bool", name: "completed", type: "bool" },
    ],
    name: "SurveyItemCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isVerified",
        type: "bool",
      },
    ],
    name: "kycStatus",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "planID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "planName",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "minAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "validatorsProfit",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "providerProfit",
        type: "uint256",
      },
      { indexed: false, internalType: "bool", name: "status", type: "bool" },
    ],
    name: "planCreated",
    type: "event",
  },
  {
    inputs: [
      { internalType: "string", name: "_planName", type: "string" },
      { internalType: "uint256", name: "_minAmount", type: "uint256" },
      {
        internalType: "uint256",
        name: "_validatorsPercentProfit",
        type: "uint256",
      },
      { internalType: "uint256", name: "_providerProfit", type: "uint256" },
      { internalType: "bool", name: "_display", type: "bool" },
    ],
    name: "addSurveyPlans",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "amountEachSurveyParticipantEarns",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "amountEachSurveyValidatorEarns",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "checkKYCStatus",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_planID", type: "uint256" },
      { internalType: "string", name: "_planName", type: "string" },
      { internalType: "uint256", name: "_minAmount", type: "uint256" },
      {
        internalType: "uint256",
        name: "_validatorsPercentProfit",
        type: "uint256",
      },
      { internalType: "uint256", name: "_providerProfit", type: "uint256" },
      { internalType: "bool", name: "_display", type: "bool" },
    ],
    name: "editSurveyPlan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "surveyURI", type: "string" },
      { internalType: "address", name: "_user", type: "address" },
      { internalType: "uint256", name: "_planID", type: "uint256" },
      { internalType: "uint256", name: "_numOfValidators", type: "uint256" },
      { internalType: "uint256", name: "_numOfcommisioners", type: "uint256" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "enrollForSurvey",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "fetchAvailableSurveys",
    outputs: [
      {
        components: [
          { internalType: "string", name: "surveyURI", type: "string" },
          { internalType: "address payable", name: "owner", type: "address" },
          { internalType: "uint256", name: "surveyID", type: "uint256" },
          { internalType: "uint256", name: "planID", type: "uint256" },
          { internalType: "uint256", name: "numOfValidators", type: "uint256" },
          {
            internalType: "uint256",
            name: "numOfcommisioners",
            type: "uint256",
          },
          { internalType: "uint256", name: "numOfresponse", type: "uint256" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "bool", name: "nftStatus", type: "bool" },
          { internalType: "bool", name: "exist", type: "bool" },
          { internalType: "bool", name: "completed", type: "bool" },
        ],
        internalType: "struct surveys.SurveyItem[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fetchMYSurveys",
    outputs: [
      {
        components: [
          { internalType: "string", name: "surveyURI", type: "string" },
          { internalType: "address payable", name: "owner", type: "address" },
          { internalType: "uint256", name: "surveyID", type: "uint256" },
          { internalType: "uint256", name: "planID", type: "uint256" },
          { internalType: "uint256", name: "numOfValidators", type: "uint256" },
          {
            internalType: "uint256",
            name: "numOfcommisioners",
            type: "uint256",
          },
          { internalType: "uint256", name: "numOfresponse", type: "uint256" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "bool", name: "nftStatus", type: "bool" },
          { internalType: "bool", name: "exist", type: "bool" },
          { internalType: "bool", name: "completed", type: "bool" },
        ],
        internalType: "struct surveys.SurveyItem[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fetchMyCompletedSurveys",
    outputs: [
      {
        components: [
          { internalType: "string", name: "surveyURI", type: "string" },
          { internalType: "address payable", name: "owner", type: "address" },
          { internalType: "uint256", name: "surveyID", type: "uint256" },
          { internalType: "uint256", name: "planID", type: "uint256" },
          { internalType: "uint256", name: "numOfValidators", type: "uint256" },
          {
            internalType: "uint256",
            name: "numOfcommisioners",
            type: "uint256",
          },
          { internalType: "uint256", name: "numOfresponse", type: "uint256" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "bool", name: "nftStatus", type: "bool" },
          { internalType: "bool", name: "exist", type: "bool" },
          { internalType: "bool", name: "completed", type: "bool" },
        ],
        internalType: "struct surveys.SurveyItem[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fetchNFTSurveys",
    outputs: [
      {
        components: [
          { internalType: "string", name: "surveyURI", type: "string" },
          { internalType: "address payable", name: "owner", type: "address" },
          { internalType: "uint256", name: "surveyID", type: "uint256" },
          { internalType: "uint256", name: "planID", type: "uint256" },
          { internalType: "uint256", name: "numOfValidators", type: "uint256" },
          {
            internalType: "uint256",
            name: "numOfcommisioners",
            type: "uint256",
          },
          { internalType: "uint256", name: "numOfresponse", type: "uint256" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "bool", name: "nftStatus", type: "bool" },
          { internalType: "bool", name: "exist", type: "bool" },
          { internalType: "bool", name: "completed", type: "bool" },
        ],
        internalType: "struct surveys.SurveyItem[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_surveyID", type: "uint256" }],
    name: "fetchSurveyAnswers",
    outputs: [
      {
        components: [
          { internalType: "string", name: "answerURI", type: "string" },
          {
            internalType: "address payable",
            name: "provider",
            type: "address",
          },
          {
            internalType: "address payable",
            name: "validator",
            type: "address",
          },
          { internalType: "uint256", name: "surveyID", type: "uint256" },
          { internalType: "uint256", name: "answerID", type: "uint256" },
          { internalType: "bool", name: "isValidated", type: "bool" },
          { internalType: "bool", name: "isValid", type: "bool" },
        ],
        internalType: "struct surveys.AnswerItem[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fetchSurveyPlans",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "planID", type: "uint256" },
          { internalType: "string", name: "planName", type: "string" },
          { internalType: "uint256", name: "minAmount", type: "uint256" },
          {
            internalType: "uint256",
            name: "validatorsProfit",
            type: "uint256",
          },
          { internalType: "uint256", name: "providerProfit", type: "uint256" },
          { internalType: "bool", name: "status", type: "bool" },
        ],
        internalType: "struct surveys.SurveyPlans[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_surveyId", type: "uint256" }],
    name: "getAmountToEarn",
    outputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "kycVerificationFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_surveyID", type: "uint256" }],
    name: "makeNFT",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_surveyID", type: "uint256" },
      { internalType: "string", name: "answerURI", type: "string" },
    ],
    name: "provideAnswer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "providerEarning",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "sonergyToken",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "surveyBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "surveyParticipantsBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "surveyValidatorsBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_answerID", type: "uint256" },
      { internalType: "uint256", name: "_surveyID", type: "uint256" },
      { internalType: "bool", name: "_isValid", type: "bool" },
    ],
    name: "validateAnswer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "validatorsEarning",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "validatorsFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "validatorsProfit",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "verifyUser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
export const SURVEY_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_TokenAddress", type: "address" },
      { internalType: "uint256", name: "_validatorsFee", type: "uint256" },
      { internalType: "uint256", name: "_kycVerificationFee", type: "uint256" },
      { internalType: "address", name: "_commisionAddress", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "surveyURI",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "validator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "surveyID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "answerID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isValidated",
        type: "bool",
      },
      { indexed: false, internalType: "bool", name: "isValid", type: "bool" },
    ],
    name: "AnswerCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "surveyURI",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "surveyID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "planID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "numOfValidators",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "numOfcommisioners",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "numOfresponse",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      { indexed: false, internalType: "bool", name: "nftStatus", type: "bool" },
      { indexed: false, internalType: "bool", name: "exist", type: "bool" },
      { indexed: false, internalType: "bool", name: "completed", type: "bool" },
    ],
    name: "SurveyItemCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isVerified",
        type: "bool",
      },
    ],
    name: "kycStatus",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "planID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "planName",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "minAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "validatorsProfit",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "providerProfit",
        type: "uint256",
      },
      { indexed: false, internalType: "bool", name: "status", type: "bool" },
    ],
    name: "planCreated",
    type: "event",
  },
  {
    inputs: [
      { internalType: "string", name: "_planName", type: "string" },
      { internalType: "uint256", name: "_minAmount", type: "uint256" },
      {
        internalType: "uint256",
        name: "_validatorsPercentProfit",
        type: "uint256",
      },
      { internalType: "uint256", name: "_providerProfit", type: "uint256" },
      { internalType: "bool", name: "_display", type: "bool" },
    ],
    name: "addSurveyPlans",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "amountEachSurveyParticipantEarns",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "amountEachSurveyValidatorEarns",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "checkKYCStatus",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_planID", type: "uint256" },
      { internalType: "string", name: "_planName", type: "string" },
      { internalType: "uint256", name: "_minAmount", type: "uint256" },
      {
        internalType: "uint256",
        name: "_validatorsPercentProfit",
        type: "uint256",
      },
      { internalType: "uint256", name: "_providerProfit", type: "uint256" },
      { internalType: "bool", name: "_display", type: "bool" },
    ],
    name: "editSurveyPlan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "surveyURI", type: "string" },
      { internalType: "address", name: "_user", type: "address" },
      { internalType: "uint256", name: "_planID", type: "uint256" },
      { internalType: "uint256", name: "_numOfValidators", type: "uint256" },
      { internalType: "uint256", name: "_numOfcommisioners", type: "uint256" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "enrollForSurvey",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "fetchAvailableSurveys",
    outputs: [
      {
        components: [
          { internalType: "string", name: "surveyURI", type: "string" },
          { internalType: "address payable", name: "owner", type: "address" },
          { internalType: "uint256", name: "surveyID", type: "uint256" },
          { internalType: "uint256", name: "planID", type: "uint256" },
          { internalType: "uint256", name: "numOfValidators", type: "uint256" },
          {
            internalType: "uint256",
            name: "numOfcommisioners",
            type: "uint256",
          },
          { internalType: "uint256", name: "numOfresponse", type: "uint256" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "bool", name: "nftStatus", type: "bool" },
          { internalType: "bool", name: "exist", type: "bool" },
          { internalType: "bool", name: "completed", type: "bool" },
        ],
        internalType: "struct surveys.SurveyItem[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fetchMYSurveys",
    outputs: [
      {
        components: [
          { internalType: "string", name: "surveyURI", type: "string" },
          { internalType: "address payable", name: "owner", type: "address" },
          { internalType: "uint256", name: "surveyID", type: "uint256" },
          { internalType: "uint256", name: "planID", type: "uint256" },
          { internalType: "uint256", name: "numOfValidators", type: "uint256" },
          {
            internalType: "uint256",
            name: "numOfcommisioners",
            type: "uint256",
          },
          { internalType: "uint256", name: "numOfresponse", type: "uint256" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "bool", name: "nftStatus", type: "bool" },
          { internalType: "bool", name: "exist", type: "bool" },
          { internalType: "bool", name: "completed", type: "bool" },
        ],
        internalType: "struct surveys.SurveyItem[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fetchMyCompletedSurveys",
    outputs: [
      {
        components: [
          { internalType: "string", name: "surveyURI", type: "string" },
          { internalType: "address payable", name: "owner", type: "address" },
          { internalType: "uint256", name: "surveyID", type: "uint256" },
          { internalType: "uint256", name: "planID", type: "uint256" },
          { internalType: "uint256", name: "numOfValidators", type: "uint256" },
          {
            internalType: "uint256",
            name: "numOfcommisioners",
            type: "uint256",
          },
          { internalType: "uint256", name: "numOfresponse", type: "uint256" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "bool", name: "nftStatus", type: "bool" },
          { internalType: "bool", name: "exist", type: "bool" },
          { internalType: "bool", name: "completed", type: "bool" },
        ],
        internalType: "struct surveys.SurveyItem[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fetchNFTSurveys",
    outputs: [
      {
        components: [
          { internalType: "string", name: "surveyURI", type: "string" },
          { internalType: "address payable", name: "owner", type: "address" },
          { internalType: "uint256", name: "surveyID", type: "uint256" },
          { internalType: "uint256", name: "planID", type: "uint256" },
          { internalType: "uint256", name: "numOfValidators", type: "uint256" },
          {
            internalType: "uint256",
            name: "numOfcommisioners",
            type: "uint256",
          },
          { internalType: "uint256", name: "numOfresponse", type: "uint256" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "bool", name: "nftStatus", type: "bool" },
          { internalType: "bool", name: "exist", type: "bool" },
          { internalType: "bool", name: "completed", type: "bool" },
        ],
        internalType: "struct surveys.SurveyItem[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_surveyID", type: "uint256" }],
    name: "fetchSurveyAnswers",
    outputs: [
      {
        components: [
          { internalType: "string", name: "answerURI", type: "string" },
          {
            internalType: "address payable",
            name: "provider",
            type: "address",
          },
          {
            internalType: "address payable",
            name: "validator",
            type: "address",
          },
          { internalType: "uint256", name: "surveyID", type: "uint256" },
          { internalType: "uint256", name: "answerID", type: "uint256" },
          { internalType: "bool", name: "isValidated", type: "bool" },
          { internalType: "bool", name: "isValid", type: "bool" },
        ],
        internalType: "struct surveys.AnswerItem[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fetchSurveyPlans",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "planID", type: "uint256" },
          { internalType: "string", name: "planName", type: "string" },
          { internalType: "uint256", name: "minAmount", type: "uint256" },
          {
            internalType: "uint256",
            name: "validatorsProfit",
            type: "uint256",
          },
          { internalType: "uint256", name: "providerProfit", type: "uint256" },
          { internalType: "bool", name: "status", type: "bool" },
        ],
        internalType: "struct surveys.SurveyPlans[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_surveyId", type: "uint256" }],
    name: "getAmountToEarn",
    outputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "kycVerificationFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_surveyID", type: "uint256" }],
    name: "makeNFT",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_surveyID", type: "uint256" },
      { internalType: "string", name: "answerURI", type: "string" },
    ],
    name: "provideAnswer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "providerEarning",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "sonergyToken",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "surveyBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "surveyParticipantsBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "surveyValidatorsBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_answerID", type: "uint256" },
      { internalType: "uint256", name: "_surveyID", type: "uint256" },
      { internalType: "bool", name: "_isValid", type: "bool" },
    ],
    name: "validateAnswer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "validatorsEarning",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "validatorsFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "validatorsProfit",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "verifyUser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
export const CONTRACT_ABI = [
  {
    inputs: [
      { internalType: "uint256", name: "initialSupply", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "spender", type: "address" },
    ],
    name: "allowance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "subtractedValue", type: "uint256" },
    ],
    name: "decreaseAllowance",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "addedValue", type: "uint256" },
    ],
    name: "increaseAllowance",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "transfer",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sender", type: "address" },
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
];
export const SURVEY_NFT_ABI = [
  {
    inputs: [
      { internalType: "address", name: "marketPlaceAddress", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "approved",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      { indexed: false, internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "ApprovalForAll",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    inputs: [
      { internalType: "uint256", name: "surveyId", type: "uint256" },
      { internalType: "uint256", name: "answerID", type: "uint256" },
    ],
    name: "answerURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "approve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "answerURI", type: "string" },
      { internalType: "uint256", name: "_surveyID", type: "uint256" },
    ],
    name: "createAnswerUri",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "surveyTokenURI", type: "string" },
    ],
    name: "createSurveyToken",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "surveyURI", type: "string" }],
    name: "createSurveyURI",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "getApproved",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "operator", type: "address" },
    ],
    name: "isApprovedForAll",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "ownerOf",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "operator", type: "address" },
      { internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "setApprovalForAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "surveyId", type: "uint256" }],
    name: "surveyURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "tokenURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export const SURVEY_MARKETPLACE_ABI = [
  {
    inputs: [
      { internalType: "uint256", name: "_surveyListingFee", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "surveyId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "fromSurveyId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "nftContract",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "surveyTokenID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address payable",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      { indexed: false, internalType: "bool", name: "status", type: "bool" },
      {
        indexed: false,
        internalType: "address payable",
        name: "seller",
        type: "address",
      },
    ],
    name: "SurveyMarketItemCreated",
    type: "event",
  },
  {
    inputs: [{ internalType: "uint256", name: "price", type: "uint256" }],
    name: "changeListingPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "nftContract", type: "address" },
      { internalType: "uint256", name: "surveyId", type: "uint256" },
    ],
    name: "createMarketSale",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "nftContract", type: "address" },
      { internalType: "uint256", name: "surveyTokenID", type: "uint256" },
      { internalType: "uint256", name: "price", type: "uint256" },
      { internalType: "uint256", name: "surveyID", type: "uint256" },
    ],
    name: "createSurveyNFT",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "fetchItemsCreated",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "surveyId", type: "uint256" },
          { internalType: "uint256", name: "fromSurveyId", type: "uint256" },
          { internalType: "address", name: "nftContract", type: "address" },
          { internalType: "uint256", name: "surveyTokenID", type: "uint256" },
          { internalType: "address payable", name: "owner", type: "address" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "bool", name: "status", type: "bool" },
          { internalType: "address payable", name: "seller", type: "address" },
        ],
        internalType: "struct surveyNFTMarket.SurveyMarketItem[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fetchMarketItems",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "surveyId", type: "uint256" },
          { internalType: "uint256", name: "fromSurveyId", type: "uint256" },
          { internalType: "address", name: "nftContract", type: "address" },
          { internalType: "uint256", name: "surveyTokenID", type: "uint256" },
          { internalType: "address payable", name: "owner", type: "address" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "bool", name: "status", type: "bool" },
          { internalType: "address payable", name: "seller", type: "address" },
        ],
        internalType: "struct surveyNFTMarket.SurveyMarketItem[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fetchUsersNFTSurveys",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "surveyId", type: "uint256" },
          { internalType: "uint256", name: "fromSurveyId", type: "uint256" },
          { internalType: "address", name: "nftContract", type: "address" },
          { internalType: "uint256", name: "surveyTokenID", type: "uint256" },
          { internalType: "address payable", name: "owner", type: "address" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "bool", name: "status", type: "bool" },
          { internalType: "address payable", name: "seller", type: "address" },
        ],
        internalType: "struct surveyNFTMarket.SurveyMarketItem[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getNFTListingPrice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
];
