import { FaHome, FaUserCircle } from "react-icons/fa";
import Button from "../components/Button";
import Logo from "../components/Logo";
import OnboardCard from "../components/OnboardCard";

export default function Home() {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className="text-3xl font-bold underline">Hello, Everything</h1>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{" "}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
    <div className="container">
      <div className="w-[100%] mobile:bg-white desktop:bg-transparent flex items-center mobile:justify-between justify-center pr-4 mb-2">
        <Logo />
        <div className="bg-primary rounded-md w-8 h-8"></div>
      </div>
      <div className="mobile:max-w-screen-mobile desktop:max-w-screen-desktop mobile:p-4 h-auto flex flex-col items-start justify-center my-0 mx-auto">
        <AccountType />
        <div className="w-[100%] flex flex-col items-center justify-end mt-14">
          <span className="text-gray-600 text-xs font-normal mb-2">
            © 2022 - Sonergy.io
          </span>
          <span className="text-gray-600 text-xs font-normal mb-2">
            Terms & conditions - Privacy policy
          </span>
        </div>
      </div>
    </div>
  );
}

const AccountType = () => (
  <>
    <OnboardCard>
      <h3 className="text-black text-lg font-medium">Select account type</h3>
      <p className="text-slate-500">
        Choose an account type that best fits your current needs for Sonergy.
      </p>
      <div className="p-6 mx-auto my-1 bg-white rounded-lg flex items-start space-x-4 border-[1px] border-solid border-[#E2EDF6] hover:border-[#0059AC] hover:cursor-pointer transition-all">
        <div className="shrink-0 p-3 rounded-md border-[1px] border-solid border-[#0059AC]">
          {/* <img class="h-12 w-12" src="/img/logo.svg" alt="User logo" /> */}
          <FaUserCircle color="#0059AC" />
        </div>
        <div>
          <div className="text-sm font-medium text-black">
            Researcher / Respondent
          </div>
          <p className="text-slate-500 text-sm">
            I am an individual, I intend to use Sonergy to create, provide
            survey data and earn rewards.
          </p>
        </div>
      </div>
      <div className="p-6 mx-auto my-1 bg-white rounded-lg flex items-start space-x-4 border-[1px] border-solid border-[#E2EDF6] hover:border-[#0059AC] hover:cursor-pointer transition-all">
        <div className="shrink-0 p-3 rounded-md border-[1px] border-solid border-[#01AAF0]">
          {/* <img class="h-12 w-12" src="/img/logo.svg" alt="User logo" /> */}
          <FaHome color="#01AAF0" />
        </div>
        <div>
          <div className="text-sm font-medium text-black">Merchant</div>
          <p className="text-slate-500 text-sm">
            I am an institution / organisation, I want to integrate Sonergy’s
            API on my application.
          </p>
        </div>
      </div>
      <Button
        text="Continue"
        onClick={(e) => console.info("Button comp clicked", e)}
      />
    </OnboardCard>
    <div className="flex items-center justify-between px-10 mt-6 w-[100%]">
      <span className="text-slate-500 text-sm">Already have an account?</span>
      <span className="text-primary text-sm">Log in</span>
    </div>
  </>
);

const NewAccount = () => {
  return (
    <>
      <OnboardCard>
        <h3 className="text-black text-lg font-medium">Create your account</h3>
        <p className="text-slate-500">
          Welcome, provide your details below to create your account.
        </p>
        <div className="p-6 mx-auto my-1 bg-white rounded-lg flex items-start space-x-4 border-[1px] border-solid border-[#E2EDF6] hover:border-[#0059AC] hover:cursor-pointer transition-all">
          <div className="shrink-0 p-3 rounded-md border-[1px] border-solid border-[#0059AC]">
            {/* <img class="h-12 w-12" src="/img/logo.svg" alt="User logo" /> */}
            <FaUserCircle color="#0059AC" />
          </div>
          <div>
            <div className="text-sm font-medium text-black">
              Researcher / Respondent
            </div>
            <p className="text-slate-500 text-sm">
              I am an individual, I intend to use Sonergy to create, provide
              survey data and earn rewards.
            </p>
          </div>
        </div>
        <div className="p-6 mx-auto my-1 bg-white rounded-lg flex items-start space-x-4 border-[1px] border-solid border-[#E2EDF6] hover:border-[#0059AC] hover:cursor-pointer transition-all">
          <div className="shrink-0 p-3 rounded-md border-[1px] border-solid border-[#01AAF0]">
            {/* <img class="h-12 w-12" src="/img/logo.svg" alt="User logo" /> */}
            <FaHome color="#01AAF0" />
          </div>
          <div>
            <div className="text-sm font-medium text-black">Merchant</div>
            <p className="text-slate-500 text-sm">
              I am an institution / organisation, I want to integrate Sonergy’s
              API on my application.
            </p>
          </div>
        </div>
        <Button
          text="Create account"
          onClick={(e) => console.info("Button comp clicked", e)}
        />
      </OnboardCard>
      <div className="flex items-center justify-between px-10 mt-6 w-[100%]">
        <span className="text-slate-500 text-sm">Already have an account?</span>
        <span className="text-primary text-sm">Log in</span>
      </div>
    </>
  );
};
